version: 0.2

env:
  shell: bash
  variables:
    PACKAGE: "github.com/ekotlikoff/gochess"


phases:
  install:
    runtime-versions:
      golang: 1.16
  install:
    commands:
      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env
      - go version
  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - go get -t ./...
  build:
    commands:
      - GOARCH=wasm GOOS=js go build -o gochessclient.wasm -tags webclient github.com/ekotlikoff/gochess/internal/client/web

artifacts:
  file: gochessclient.wasm
